# Generated by Django 5.2 on 2025-04-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reportcolumns_reports_roleandreportrelation_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleandreportrelation',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
