# Generated by Django 5.2 on 2025-04-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_updated_roleandreportrelation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcolumns',
            name='created_at',
        ),
        migrations.CreateModel(
            name='ReportColumnPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcolumns')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
    ]
