# Generated by Django 5.2 on 2025-04-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reportcolumns_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleandreportrelation',
            old_name='report_column_id',
            new_name='report_id',
        ),
        migrations.RemoveField(
            model_name='roleandreportrelation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roleandreportrelation',
            name='updated_at',
        ),
    ]
