# Generated by Django 5.2 on 2025-04-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_report_column_id_roleandreportrelation_report_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcolumnpermission',
            old_name='column_id',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='reportcolumnpermission',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='reportcolumnpermission',
            old_name='role_id',
            new_name='role',
        ),
    ]
