# Generated by Django 5.2 on 2025-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_column_id_reportcolumnpermission_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reports',
            name='template_count',
            field=models.IntegerField(default=0),
        ),
    ]
