# Generated by Django 5.2 on 2025-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reporttemplates_templatecolumns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecolumns',
            name='column_id',
        ),
        migrations.AddField(
            model_name='templatecolumns',
            name='column_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
