# Generated by Django 5.2 on 2025-04-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_templatecolumns_column_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecolumns',
            name='report_id',
        ),
    ]
