# Generated by Django 5.2 on 2025-04-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_templatecolumns_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplates',
            name='parent_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='api.reports'),
        ),
        migrations.AlterField(
            model_name='templatecolumns',
            name='template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='api.reporttemplates'),
        ),
    ]
