# Generated by Django 5.2 on 2025-04-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_reporttemplates_parent_report_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttemplates',
            old_name='parent_report_id',
            new_name='parent_report',
        ),
    ]
