# Generated by Django 5.2 on 2025-04-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_parent_report_id_reporttemplates_parent_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecolumns',
            old_name='template_id',
            new_name='template',
        ),
    ]
