# Generated by Django 5.2 on 2025-04-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_template_id_templatecolumns_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumns',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_columns', to='api.reports'),
        ),
    ]
