# Generated by Django 5.2 on 2025-04-25 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_reportcolumns_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='template_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
