# Generated by Django 5.2 on 2025-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_reports_template_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplates',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
