# Generated by Django 5.2 on 2025-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_reporttemplates_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplates',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
