# Generated by Django 5.2 on 2025-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_reporttemplates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecolumns',
            name='label',
            field=models.CharField(default='label', max_length=200),
        ),
    ]
