# Generated by Django 5.2 on 2025-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_templatecolumns_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='label',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
