# Generated by Django 5.2 on 2025-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reports_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='label',
        ),
        migrations.AddField(
            model_name='reportcolumns',
            name='label',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
