# Generated by Django 5.2 on 2025-04-28 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_reports_label_reportcolumns_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
                ('filter_label', models.CharField(max_length=255)),
                ('exist_in_report', models.BooleanField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_filters', to='api.reports')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
                ('filter_label', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_filter', to='api.reportcolumns')),
            ],
        ),
    ]
