# Generated by Django 5.2 on 2025-04-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_reportfilters_templatefilters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcolumnpermission',
            name='column',
        ),
        migrations.RemoveField(
            model_name='reportcolumnpermission',
            name='report',
        ),
    ]
