# Generated by Django 5.2 on 2025-04-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_reportcolumnpermission_column_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcolumns',
            old_name='report_id',
            new_name='report',
        ),
    ]
