# Generated by Django 5.2 on 2025-04-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_report_id_reportcolumns_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefilters',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_filter', to='api.reporttemplates'),
        ),
    ]
