# Generated by Django 5.2 on 2025-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_templatefilters_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfilters',
            name='filter_type',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='reportfilters',
            name='is_compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
