# Generated by Django 5.2 on 2025-05-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reportfilters_filter_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to='api.reports')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(default=1)),
                ('field_name', models.CharField(max_length=255)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('column', 'Column'), ('filter', 'Filter')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.templatemaster')),
            ],
        ),
    ]
