# Generated by Django 5.2 on 2025-05-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reportfilters_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecolumns',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_column_source', to='api.reports'),
        ),
        migrations.AddField(
            model_name='templatefilters',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_filter_source', to='api.reports'),
        ),
        migrations.CreateModel(
            name='TemplateReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_templates', to='api.reports')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_reports', to='api.reporttemplates')),
            ],
        ),
    ]
