# Generated by Django 5.2 on 2025-05-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reportfilters_filter_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.reporttemplatemaster')),
            ],
        ),
    ]
