# Generated by Django 5.2 on 2025-05-02 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_templatemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(default=1)),
                ('field_name', models.CharField(max_length=255)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('column', 'Column'), ('filter', 'Filter')], max_length=10)),
                ('filter_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.templatemaster')),
            ],
        ),
    ]
