# Generated by Django 5.2 on 2025-05-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_templatecolumns_report_templatefilters_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecolumns',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_column_source', to='api.reports'),
        ),
        migrations.AlterField(
            model_name='templatefilters',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_filter_source', to='api.reports'),
        ),
    ]
