# Generated by Django 5.2 on 2025-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_reporttemplatemaster_reporttemplatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplatedetails',
            name='user_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
