# Generated by Django 5.2 on 2025-05-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_templatedetails'),
        ('api', '0028_migrate_template_data'),
    ]

    operations = [
    ]
