# Generated by Django 5.2 on 2025-05-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_0027_templatedetails_0028_migrate_template_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatedetails',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='templatedetails',
            name='is_compulsory',
        ),
    ]
