# Generated by Django 5.2 on 2025-05-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_templatedetails_filter_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemaster',
            old_name='report',
            new_name='parent_report',
        ),
    ]
